data_config:
  source:
    type: "hf"
    repo_id: "glaiveai/glaive-code-assistant-v2"
    config_name: "default"
    split: "train"

    transformations:
      - transform: sygra.processors.data_transform.RenameFieldsTransform
        params:
          mapping:
            task_id: id
          overwrite: false

graph_config:
  nodes:
    generate_answer:
      node_type: llm
      prompt:
        - system: |
            You are a skilled writer who is very good at paraphrasing or writing similar content to a another piece of text given to you.

            You will write a very well and detailed rephrasing of the given content, without missing any key information.
        - user: |
            Content: {question}
      model:
        name: gpt-4o
        parameters:
          temperature: 0.1

  edges:
    - from: START
      to: generate_answer
    - from: generate_answer
      to: END

output_config:
  generator: tasks.examples.glaive_code_assistant.task_executor.CodeGenOutputGenerator

  output_map:
    id:
      from: "id"
    conversation:
      from: "messages"
      transform: "build_conversation"
    taxonomy:
      value:
        - category: "Coding"
          subcategory: ""
    annotation_type:
      value: [ "gpt4o" ]
    language:
      value: "en"
    tags:
      value: ["glaiveai/glaive-code-assistant-v2", "reannotate", "self-critique"]
